### PR TITLE
Release v0.4.2

### PR DESCRIPTION
**Pull request by ulupo**

### CODE REVIEW

**Comment by MonkeyBreaker** [comment]
@ulupo Daniel merged my last PR for flagser, this one introduces 2 things:

1. flagser has some inner parallelism, which was always set to 8 threads, now this value can be configured
2. @gtauzin reported me that sometimes when an error is encountered inside of the C++, the C++ produces an `exit` statement, which produces strange behavior. Now all the exit where replaces by exception and I think that we should be able to catch them inside of Python.

Would you like a PR about this for this version ?

**Comment by ulupo** [comment]
@MonkeyBreaker I think I updated `flagser` already as part of #50.  But I forgot to write about your update in the relase notes! So I will now.

**Comment by ulupo** [comment]
But @MonkeyBreaker I now see that you have prepared a PR to fix #49.  So maybe we can include this for 0.4.2.

**Comment by MonkeyBreaker** [comment]
> I think I updated flagser already as part of #50. But I forgot to write about your update in the relase notes! So I will now.

Definitely, my fault I did not see your PR.

> But @MonkeyBreaker I now see that you have prepared a PR to fix #49. So maybe we can include this for 0.4.2.

I'm preparing it, it should finish this afternoon

**Comment by ulupo** [comment]
> I'm preparing it, it should finish this afternoon

Awesome!  Do you mind adding a small description of it and of the previous flagser update in `RELEASE.rst`? It doesn't have to be perfect, I'll adjust it if needed.

**Comment by MonkeyBreaker** [comment]
Sure, so I update the `Release.rst` file currently present in Master ?

**Pull request closed without merging**
