### PR TITLE
Update arguments

### PR DESCRIPTION
**Pull request by reds-heig**
#### Reference Issues/PRs

#45 

#### What does this implement/fix? Explain your changes.

This PR integrates commit 702938a from `flagser`.
This commit introduces a new way of managing the parameters forwarded to `flagser`.
Now instead of recreating virtual command line arguments, a new class, `flagser_parameters` is filled with the corresponding fields.

This class contain all the parameters managed in `flagser`, but in our case, the following ones are unused (but could be used in the future of course):

```cpp
// Unused parameters for pyflagser
// threshold <std::numeric_limits<value_t>::max()>
// split_into_connected_components <false>
// input_format <flagser> (not used)
// output_format <barcode> (not used)
// cache <""> (not used)
// cache <""> (not used)
```

Adding new test is in progress, but I'm struggling with the following:

* `pytest` seems to not be able to manage timeouts in itself, it requires an extension [pytest-timeout](https://pypi.org/project/pytest-timeout/), shall we add it as a dependency ? 
  * the reason why I require a timeout is because the issue encounter in #45, does not generates an error, but runs indefinitely -> a timeout mechanism should be available in our test
* I'm not an expert in `pytest` but when I add a new test, it's run for each available dataset, even if I don't need the dataset, does anyone have a solution for this ?

### CODE REVIEW

**Comment by MonkeyBreaker** [comment]
Why ...

One of the windows finished, but the other ones seems to timeout.
Does the azure pipeline implement some kind of global timeout ?

**Comment by MonkeyBreaker** [comment]
@ulupo, the issue reports a run that doesn't end, which is an error. In order to add a test for this issue and prevent encountering in the future, it's necessary to be able to catch this problem on our test.

As far as I understood with `pytest`, testing something that never ends, cannot be done out of the box, you need a new package `pytest-timeout`. This package allows to me add a timeout to a test, which if the test doesn't finish it let's say, 3 seconds, it's because something goes wrong.

And just to not mix things, apparently, the pipeline generates a timeout, that isn't unrelated to the issue I report just before, but apparently the test on the pipeline takes too much time.

**Comment by ulupo** [comment]
@MonkeyBreaker thanks for the reply!  Sorry for insisting, but my question was not clear.  I meant to say "if the issue is fixed, how can we even test it in principle?".

**Comment by MonkeyBreaker** [comment]
@ulupe, no worries :), it's better that I explain better if it's not clear enough.

A good practice after fixing an issue reported by library users, is to add a test case that reproduced the error.
Even if after the fix, the issue does not arise, but maybe in the future, with future updates of `pyflagser` or `flagser`, this issue could or something similar could arise again, and could then be catch before merging to master.

That's why I would like to add it as a test.

**Comment by ulupo** [comment]
@MonkeyBreaker thanks for the reply. Still, I am not sure I follow what exactly you'd like to test. The way I see it, the issue is fixed, so normal behaviour should now be that the new test goes through, while abnormal behaviour should be that the test does not terminate, resulting presumably in an error. So what is the need to set timeouts, and how exactly would you like to set them?

**Comment by ulupo** [comment]
@MonkeyBreaker why is the parameter `threshold ` unused? It seems to me it should play the role of `max_edge_weight` in https://github.com/giotto-ai/pyflagser/blob/28b71349443e247a0033f949793a8b1016e6addb/pyflagser/flagser.py#L116 (a bit like `thresh` in the ripser interface of `giotto-tda`.

**Comment by MonkeyBreaker** [comment]
@ulupo, as far as I understood, in `flagser`, the `threshold` argument is only used when computing `Rips complexess`, we don't use this option in this library.

`max_edge_weight` is only used inside our library as a parameter for the [_extract_weighted_graph](https://github.com/giotto-ai/pyflagser/blob/28b71349443e247a0033f949793a8b1016e6addb/pyflagser/_utils.py#L37) function.

Maybe you can discuss more on this with @gtauzin directly ?

**Comment by ulupo** [comment]
@MonkeyBreaker thanks. Of course you're right about the use of `max_edge_weight`. Still, I thought passing `directed=False` meant computing Rips complexes, so we should be passing a threshold to `flagser` then, even it if it is infinite?

**Comment by ulupo** [comment]
@MonkeyBreaker I've added the timeouts. If/when the CI passes, are you happy for me to merge?

**Comment by MonkeyBreaker** [comment]
Perfect for me if all test pass ! :+1:

**Pull request merged**
